# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee3de175f78479eda14ed121d91e650035c14162d5237223ca1186aab4af006767ae9e289161e8ec17e6b643860db25c0945e3b505f4b1d041b11cc909c7be1a

test:
  secret_key_base: c8b7f4b5a43752138059fb6c1dcc9cbc0e34e45eb15abce28eedd8e91b4ae6c802d19ae9106d84992d5b0cdc122d019e63fa71212d323302813bf3f64194a3e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
